"""add backup config

Revision ID: 93a6c7fd187f
Revises: cf4079a3cebc
Create Date: 2025-01-23 09:26:43.650577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a6c7fd187f'
down_revision = 'cf4079a3cebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('backup_time', sa.String(length=5), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_config')
    # ### end Alembic commands ###
