"""Added email column to User model

Revision ID: cf4079a3cebc
Revises: 6610ecba9317
Create Date: 2025-01-22 22:27:25.383553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4079a3cebc'
down_revision = '6610ecba9317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_history_user_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index('idx_chat_history_user_timestamp', ['user_id', 'timestamp'], unique=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
