services:
  edxo:
    build: .
    # Run multiple ASGI workers; preload to avoid duplicate app init per worker
    command: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000 -c src/config/gunicorn.conf.py --preload --timeout 500 --keep-alive 75 src.asgi:app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Assure que Flask/Celery parlent au conteneur Redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - txt_outputs:/app/src/txt_outputs
      - pdfs:/app/src/pdfs_downloaded
      - uploads:/app/src/uploads
      - db_data:/app/src/database
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:alpine
    # Disable persistence to avoid restoring old Celery tasks on restart
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    # Keep Redis data purely in-memory for dev; ensures clean state on container restart
    tmpfs:
      - /data
    # No host port mapping needed; used only on internal network
  celery:
    build: .
    command: celery -A src.celery_app:celery worker --loglevel=info --autoscale=8,2 -Ofair --prefetch-multiplier=1 --hostname=worker2@%h
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_WORKER=1
    volumes:
      - txt_outputs:/app/src/txt_outputs
      - pdfs:/app/src/pdfs_downloaded
      - uploads:/app/src/uploads
      - db_data:/app/src/database
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  txt_outputs: {}
  pdfs: {}
  uploads: {}
  db_data: {}
