services:
  edxo:
    build: .
    # Run multiple ASGI workers to avoid SSE blocking other requests
    command: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000 src.asgi:app --timeout 500 --keep-alive 75
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Assure que Flask/Celery parlent au conteneur Redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - txt_outputs:/app/src/txt_outputs
      - pdfs:/app/src/pdfs_downloaded
      - uploads:/app/src/uploads
      - db_data:/app/src/database
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:alpine
    # No host port mapping needed; used only on internal network
  celery:
    build: .
    command: celery -A src.celery_app:celery worker --loglevel=info --hostname=worker2@%h
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - txt_outputs:/app/src/txt_outputs
      - pdfs:/app/src/pdfs_downloaded
      - uploads:/app/src/uploads
      - db_data:/app/src/database
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  txt_outputs: {}
  pdfs: {}
  uploads: {}
  db_data: {}
