"""empty message

Revision ID: 145ed415b3f9
Revises: 
Create Date: 2025-02-14 20:59:11.608083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145ed415b3f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FilConducteur', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_filconducteur_programme', 'Programme', ['programme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FilConducteur', schema=None) as batch_op:
        batch_op.drop_constraint('fk_filconducteur_programme', type_='foreignkey')

    # ### end Alembic commands ###
