"""empty message

Revision ID: 15a23c456ef5
Revises: 8aaf4fd4a35e
Create Date: 2025-02-14 09:52:55.675055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a23c456ef5'
down_revision = '8aaf4fd4a35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailgun_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailgun_domain', sa.String(length=255), nullable=False),
    sa.Column('mailgun_api_key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailgun_config')
    # ### end Alembic commands ###
