"""empty message

Revision ID: 18cb5c536f76
Revises: 
Create Date: 2025-01-27 13:04:44.841167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cb5c536f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_savoirfaire', schema=None) as batch_op:
        batch_op.alter_column('capacite_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_savoirfaire', schema=None) as batch_op:
        batch_op.alter_column('capacite_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
