"""empty message

Revision ID: 19b209438a4e
Revises: b6d007ad4e76
Create Date: 2025-04-26 21:25:41.760502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b209438a4e'
down_revision = 'b6d007ad4e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('function_call_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('function_call_args', sa.Text(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('function_call_args')
        batch_op.drop_column('function_call_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
