"""empty message

Revision ID: 22b9790b5457
Revises: 
Create Date: 2025-01-27 20:55:18.344042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b9790b5457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DBChange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=10), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_dbchange_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_savoirfaire',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('savoir_faire_id', sa.Integer(), nullable=False),
    sa.Column('capacite_id', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('level1_description', sa.String(length=255), nullable=True),
    sa.Column('level2_description', sa.String(length=255), nullable=True),
    sa.Column('level3_description', sa.String(length=255), nullable=True),
    sa.Column('level4_description', sa.String(length=255), nullable=True),
    sa.Column('level5_description', sa.String(length=255), nullable=True),
    sa.Column('level6_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['capacite_id'], ['PlanCadreCapacites.id'], name='fk_evaluation_savoirfaire_capacite'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['PlanDeCoursEvaluations.id'], name='fk_evaluation_savoirfaire_evaluation'),
    sa.ForeignKeyConstraint(['savoir_faire_id'], ['PlanCadreCapaciteSavoirsFaire.id'], name='fk_evaluation_savoirfaire_savoirfaire'),
    sa.PrimaryKeyConstraint('evaluation_id', 'savoir_faire_id', name='pk_evaluation_savoirfaire')
    )
    with op.batch_alter_table('Cours', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cours_filconducteur', 'FilConducteur', ['fil_conducteur_id'], ['id'])

    with op.batch_alter_table('GlobalGenerationSettings', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('PlanDeCoursEvaluationsCapacites', schema=None) as batch_op:
        batch_op.alter_column('capacite_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanDeCoursEvaluationsCapacites', schema=None) as batch_op:
        batch_op.alter_column('capacite_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('GlobalGenerationSettings', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Cours', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cours_filconducteur', type_='foreignkey')

    op.drop_table('evaluation_savoirfaire')
    op.drop_table('DBChange')
    # ### end Alembic commands ###
