"""add gestion des prompts pour grille d'évaluation

Revision ID: 284e3b818ea8
Revises: 22b9790b5457
Create Date: 2025-01-28 11:28:07.916582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284e3b818ea8'
down_revision = '22b9790b5457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grille_prompt_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('level1_description', sa.Text(), nullable=False),
    sa.Column('level2_description', sa.Text(), nullable=False),
    sa.Column('level3_description', sa.Text(), nullable=False),
    sa.Column('level4_description', sa.Text(), nullable=False),
    sa.Column('level5_description', sa.Text(), nullable=False),
    sa.Column('level6_description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grille_prompt_settings')
    # ### end Alembic commands ###
