"""empty message

Revision ID: 34fb8dfb9125
Revises: bc45b7dcd4ad
Create Date: 2025-01-27 06:36:20.513524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fb8dfb9125'
down_revision = 'bc45b7dcd4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanDeCoursEvaluationsCapacites', schema=None) as batch_op:
        batch_op.alter_column('capacite_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanDeCoursEvaluationsCapacites', schema=None) as batch_op:
        batch_op.alter_column('capacite_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
