"""empty message

Revision ID: 44e9c9187ee3
Revises: 840aecbb1b1f
Create Date: 2025-01-30 13:20:32.614810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e9c9187ee3'
down_revision = '840aecbb1b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyse_plan_cours_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyse_plan_cours_prompt')
    # ### end Alembic commands ###
