"""empty message

Revision ID: 5d66884c1ad2
Revises: 
Create Date: 2025-01-30 21:55:36.132211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d66884c1ad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_chathistory_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_PlanDeCours')
    with op.batch_alter_table('PlanDeCours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_plan_de_cours_modified_by', 'User', ['modified_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanDeCours', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plan_de_cours_modified_by', type_='foreignkey')
        batch_op.drop_column('modified_by_id')

    op.create_table('_alembic_tmp_PlanDeCours',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cours_id', sa.INTEGER(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('session', sa.TEXT(), nullable=False),
    sa.Column('campus', sa.TEXT(), nullable=True),
    sa.Column('nom_enseignant', sa.TEXT(), nullable=True),
    sa.Column('telephone_enseignant', sa.TEXT(), nullable=True),
    sa.Column('courriel_enseignant', sa.TEXT(), nullable=True),
    sa.Column('bureau_enseignant', sa.TEXT(), nullable=True),
    sa.Column('presentation_du_cours', sa.TEXT(), nullable=True),
    sa.Column('objectif_terminal_du_cours', sa.TEXT(), nullable=True),
    sa.Column('organisation_et_methodes', sa.TEXT(), nullable=True),
    sa.Column('accomodement', sa.TEXT(), nullable=True),
    sa.Column('evaluation_formative_apprentissages', sa.TEXT(), nullable=True),
    sa.Column('evaluation_expression_francais', sa.TEXT(), nullable=True),
    sa.Column('seuil_reussite', sa.TEXT(), nullable=True),
    sa.Column('place_et_role_du_cours', sa.TEXT(), nullable=True),
    sa.Column('materiel', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('compatibility_percentage', sa.FLOAT(), nullable=True),
    sa.Column('recommendation_ameliore', sa.TEXT(), nullable=True),
    sa.Column('recommendation_plan_cadre', sa.TEXT(), nullable=True),
    sa.Column('modified_at', sa.DATETIME(), nullable=True),
    sa.Column('modified_by_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['Cours.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['User.id'], name='fk_plan_de_cours_modified_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_history')
    # ### end Alembic commands ###
