"""empty message

Revision ID: 727327e2cc2f
Revises: 15a23c456ef5
Create Date: 2025-02-14 11:01:18.259335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727327e2cc2f'
down_revision = '15a23c456ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('reset_version')

    # ### end Alembic commands ###
