"""empty message

Revision ID: 7e053a0768ed
Revises: 5d66884c1ad2
Create Date: 2025-01-30 22:37:38.073963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e053a0768ed'
down_revision = '5d66884c1ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanCadre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_plan_cadre_modified_by', 'User', ['modified_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanCadre', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plan_cadre_modified_by', type_='foreignkey')
        batch_op.drop_column('modified_at')
        batch_op.drop_column('modified_by_id')

    # ### end Alembic commands ###
