"""empty message

Revision ID: 840aecbb1b1f
Revises: d6b999a018f8
Create Date: 2025-01-30 10:56:13.470461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840aecbb1b1f'
down_revision = 'd6b999a018f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanDeCours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatibility_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recommendation_ameliore', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommendation_plan_cadre', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanDeCours', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('recommendation_plan_cadre')
        batch_op.drop_column('recommendation_ameliore')
        batch_op.drop_column('compatibility_percentage')

    # ### end Alembic commands ###
