"""empty message

Revision ID: 8aaf4fd4a35e
Revises: 
Create Date: 2025-02-03 17:49:54.327806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aaf4fd4a35e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('input_price', sa.Float(), nullable=False),
    sa.Column('output_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('PlanCadre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_plan_cadre_modified_by', 'User', ['modified_by_id'], ['id'])

    with op.batch_alter_table('PlanDeCours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_plan_de_cours_modified_by', 'User', ['modified_by_id'], ['id'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nom', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prenom', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_first_connexion', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    with op.batch_alter_table('analyse_plan_cours_prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model', sa.String(length=50), server_default='gpt-4o', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyse_plan_cours_prompt', schema=None) as batch_op:
        batch_op.drop_column('ai_model')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_first_connexion')
        batch_op.drop_column('prenom')
        batch_op.drop_column('nom')
        batch_op.drop_column('image')

    with op.batch_alter_table('PlanDeCours', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plan_de_cours_modified_by', type_='foreignkey')
        batch_op.drop_column('modified_by_id')

    with op.batch_alter_table('PlanCadre', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plan_cadre_modified_by', type_='foreignkey')
        batch_op.drop_column('modified_at')
        batch_op.drop_column('modified_by_id')

    op.drop_table('openai_models')
    # ### end Alembic commands ###
