"""Recreate backup_config table

Revision ID: bc45b7dcd4ad
Revises: 
Create Date: 2025-01-26 22:09:43.908433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc45b7dcd4ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DBChange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=10), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_dbchange_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Cours', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cours_filconducteur', 'FilConducteur', ['fil_conducteur_id'], ['id'])

    with op.batch_alter_table('GlobalGenerationSettings', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalGenerationSettings', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Cours', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cours_filconducteur', type_='foreignkey')

    op.drop_table('DBChange')
    # ### end Alembic commands ###
