"""empty message

Revision ID: d3dd80c3a641
Revises: 
Create Date: 2025-01-31 14:36:39.749382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3dd80c3a641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyse_plan_cours_prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model', sa.String(length=50), server_default='gpt-4o', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyse_plan_cours_prompt', schema=None) as batch_op:
        batch_op.drop_column('ai_model')

    # ### end Alembic commands ###
