"""empty message

Revision ID: d420453e4321
Revises: 
Create Date: 2025-08-27 11:32:55.657505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd420453e4321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for idempotency ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    existing_tables = set(insp.get_table_names())

    if 'CompetenceCoursOverride' in existing_tables:
        op.drop_table('CompetenceCoursOverride')
    if 'dummy' in existing_tables:
        op.drop_table('dummy')

    existing_indexes = {ix['name'] for ix in insp.get_indexes('User')}
    existing_uniques = {uc['name'] for uc in insp.get_unique_constraints('User') if uc.get('name')}

    with op.batch_alter_table('User', schema=None) as batch_op:
        # Drop legacy unique index then add a named unique constraint
        if 'ux_user_api_token' in existing_indexes:
            batch_op.drop_index('ux_user_api_token')
        if 'uq_user_api_token' not in existing_uniques:
            batch_op.create_unique_constraint('uq_user_api_token', ['api_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_api_token', type_='unique')
        batch_op.create_index('ux_user_api_token', ['api_token'], unique=1)

    op.create_table('dummy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CompetenceCoursOverride',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('programme_id', sa.INTEGER(), nullable=False),
    sa.Column('cours_id', sa.INTEGER(), nullable=False),
    sa.Column('competence_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['User.id'], name='fk_ccoverride_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'cours_id', 'competence_id', name='uq_override_prog_cours_comp')
    )
    # ### end Alembic commands ###
