"""empty message

Revision ID: d805d64ad9a7
Revises: a980783ec51d
Create Date: 2025-01-27 13:36:21.404645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd805d64ad9a7'
down_revision = 'a980783ec51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_savoirfaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level1_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('level2_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('level3_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('level4_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('level5_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('level6_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_savoirfaire', schema=None) as batch_op:
        batch_op.drop_column('level6_description')
        batch_op.drop_column('level5_description')
        batch_op.drop_column('level4_description')
        batch_op.drop_column('level3_description')
        batch_op.drop_column('level2_description')
        batch_op.drop_column('level1_description')

    # ### end Alembic commands ###
