"""empty message

Revision ID: f0c85ed20c03
Revises: 
Create Date: 2025-01-30 20:17:00.772126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c85ed20c03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyse_plan_cours_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_de_cours_prompt_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('context_variables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_chathistory_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('PlanDeCours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatibility_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recommendation_ameliore', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommendation_plan_cadre', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PlanDeCours', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('recommendation_plan_cadre')
        batch_op.drop_column('recommendation_ameliore')
        batch_op.drop_column('compatibility_percentage')

    op.drop_table('chat_history')
    op.drop_table('plan_de_cours_prompt_settings')
    op.drop_table('analyse_plan_cours_prompt')
    # ### end Alembic commands ###
