"""Recreating database

Revision ID: 6610ecba9317
Revises: 
Create Date: 2025-01-22 22:18:57.928153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6610ecba9317'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Competence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('criteria_de_performance', sa.Text(), nullable=True),
    sa.Column('contexte_de_realisation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CompetenceParCours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('competence_developpee_id', sa.Integer(), nullable=False),
    sa.Column('competence_atteinte_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CoursCorequis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('cours_corequis_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CoursPrealable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('cours_prealable_id', sa.Integer(), nullable=False),
    sa.Column('note_necessaire', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ElementCompetenceParCours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('element_competence_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='Non traité', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FilConducteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('couleur', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GlobalGenerationSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('use_ai', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('text_content', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ListeCegep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), server_default='Public', nullable=False),
    sa.Column('region', sa.Text(), server_default='Capitale-Nationale', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ListeProgrammeMinisteriel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('cegep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cegep_id'], ['ListeCegep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ElementCompetence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['Competence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DepartmentPIEA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['Department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DepartmentRegles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('regle', sa.Text(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['Department.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('DepartmentRegles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DepartmentRegles_department_id'), ['department_id'], unique=False)

    op.create_table('ElementCompetenceCriteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_competence_id', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['element_competence_id'], ['ElementCompetence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('liste_programme_ministeriel_id', sa.Integer(), nullable=True),
    sa.Column('cegep_id', sa.Integer(), nullable=True),
    sa.Column('variante', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cegep_id'], ['ListeCegep.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['Department.id'], ),
    sa.ForeignKeyConstraint(['liste_programme_ministeriel_id'], ['ListeProgrammeMinisteriel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='invite', nullable=False),
    sa.Column('openai_key', sa.Text(), nullable=True),
    sa.Column('cegep_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cegep_id'], ['ListeCegep.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['Department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('nombre_unites', sa.Float(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('heures_theorie', sa.Integer(), nullable=False),
    sa.Column('heures_laboratoire', sa.Integer(), nullable=False),
    sa.Column('heures_travail_maison', sa.Integer(), nullable=False),
    sa.Column('fil_conducteur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['Programme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_Programme',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['Programme.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'programme_id')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('place_intro', sa.Text(), nullable=True),
    sa.Column('objectif_terminal', sa.Text(), nullable=True),
    sa.Column('structure_intro', sa.Text(), nullable=True),
    sa.Column('structure_activites_theoriques', sa.Text(), nullable=True),
    sa.Column('structure_activites_pratiques', sa.Text(), nullable=True),
    sa.Column('structure_activites_prevues', sa.Text(), nullable=True),
    sa.Column('eval_evaluation_sommative', sa.Text(), nullable=True),
    sa.Column('eval_nature_evaluations_sommatives', sa.Text(), nullable=True),
    sa.Column('eval_evaluation_de_la_langue', sa.Text(), nullable=True),
    sa.Column('eval_evaluation_sommatives_apprentissages', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.Text(), server_default='gpt-4o', nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['Cours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanDeCours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('session', sa.Text(), nullable=False),
    sa.Column('campus', sa.Text(), nullable=True),
    sa.Column('nom_enseignant', sa.Text(), nullable=True),
    sa.Column('telephone_enseignant', sa.Text(), nullable=True),
    sa.Column('courriel_enseignant', sa.Text(), nullable=True),
    sa.Column('bureau_enseignant', sa.Text(), nullable=True),
    sa.Column('presentation_du_cours', sa.Text(), nullable=True),
    sa.Column('objectif_terminal_du_cours', sa.Text(), nullable=True),
    sa.Column('organisation_et_methodes', sa.Text(), nullable=True),
    sa.Column('accomodement', sa.Text(), nullable=True),
    sa.Column('evaluation_formative_apprentissages', sa.Text(), nullable=True),
    sa.Column('evaluation_expression_francais', sa.Text(), nullable=True),
    sa.Column('seuil_reussite', sa.Text(), nullable=True),
    sa.Column('place_et_role_du_cours', sa.Text(), nullable=True),
    sa.Column('materiel', sa.Text(), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['Cours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCapacites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cadre_id', sa.Integer(), nullable=False),
    sa.Column('capacite', sa.Text(), nullable=False),
    sa.Column('description_capacite', sa.Text(), nullable=True),
    sa.Column('ponderation_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ponderation_max', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['plan_cadre_id'], ['PlanCadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCompetencesCertifiees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cadre_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_cadre_id'], ['PlanCadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCompetencesDeveloppees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cadre_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_cadre_id'], ['PlanCadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCoursCorequis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cadre_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_cadre_id'], ['PlanCadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCoursPrealables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cadre_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_cadre_id'], ['PlanCadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCoursRelies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cadre_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_cadre_id'], ['PlanCadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreObjetsCibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cadre_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_cadre_id'], ['PlanCadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreSavoirEtre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cadre_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plan_cadre_id'], ['PlanCadre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanDeCoursCalendrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_de_cours_id', sa.Integer(), nullable=False),
    sa.Column('semaine', sa.Integer(), nullable=True),
    sa.Column('sujet', sa.Text(), nullable=True),
    sa.Column('activites', sa.Text(), nullable=True),
    sa.Column('travaux_hors_classe', sa.Text(), nullable=True),
    sa.Column('evaluations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_de_cours_id'], ['PlanDeCours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanDeCoursDisponibiliteEnseignant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_de_cours_id', sa.Integer(), nullable=False),
    sa.Column('jour_semaine', sa.Text(), nullable=True),
    sa.Column('plage_horaire', sa.Text(), nullable=True),
    sa.Column('lieu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_de_cours_id'], ['PlanDeCours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanDeCoursEvaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_de_cours_id', sa.Integer(), nullable=False),
    sa.Column('titre_evaluation', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('semaine', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_de_cours_id'], ['PlanDeCours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanDeCoursMediagraphie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_de_cours_id', sa.Integer(), nullable=False),
    sa.Column('reference_bibliographique', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_de_cours_id'], ['PlanDeCours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCapaciteMoyensEvaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacite_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['capacite_id'], ['PlanCadreCapacites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCapaciteSavoirsFaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacite_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('cible', sa.Text(), nullable=True),
    sa.Column('seuil_reussite', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capacite_id'], ['PlanCadreCapacites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanCadreCapaciteSavoirsNecessaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacite_id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['capacite_id'], ['PlanCadreCapacites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanDeCoursEvaluationsCapacites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('capacite_id', sa.Integer(), nullable=False),
    sa.Column('ponderation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capacite_id'], ['PlanCadreCapacites.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['PlanDeCoursEvaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlanDeCoursEvaluationsCapacites')
    op.drop_table('PlanCadreCapaciteSavoirsNecessaires')
    op.drop_table('PlanCadreCapaciteSavoirsFaire')
    op.drop_table('PlanCadreCapaciteMoyensEvaluation')
    op.drop_table('PlanDeCoursMediagraphie')
    op.drop_table('PlanDeCoursEvaluations')
    op.drop_table('PlanDeCoursDisponibiliteEnseignant')
    op.drop_table('PlanDeCoursCalendrier')
    op.drop_table('PlanCadreSavoirEtre')
    op.drop_table('PlanCadreObjetsCibles')
    op.drop_table('PlanCadreCoursRelies')
    op.drop_table('PlanCadreCoursPrealables')
    op.drop_table('PlanCadreCoursCorequis')
    op.drop_table('PlanCadreCompetencesDeveloppees')
    op.drop_table('PlanCadreCompetencesCertifiees')
    op.drop_table('PlanCadreCapacites')
    op.drop_table('PlanDeCours')
    op.drop_table('PlanCadre')
    op.drop_table('chat_history')
    op.drop_table('User_Programme')
    op.drop_table('Cours')
    op.drop_table('User')
    op.drop_table('Programme')
    op.drop_table('ElementCompetenceCriteria')
    with op.batch_alter_table('DepartmentRegles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DepartmentRegles_department_id'))

    op.drop_table('DepartmentRegles')
    op.drop_table('DepartmentPIEA')
    op.drop_table('ElementCompetence')
    op.drop_table('Department')
    op.drop_table('ListeProgrammeMinisteriel')
    op.drop_table('ListeCegep')
    op.drop_table('GlobalGenerationSettings')
    op.drop_table('FilConducteur')
    op.drop_table('ElementCompetenceParCours')
    op.drop_table('CoursPrealable')
    op.drop_table('CoursCorequis')
    op.drop_table('CompetenceParCours')
    op.drop_table('Competence')
    # ### end Alembic commands ###
