"""add db tracking

Revision ID: c534224e57c1
Revises: 93a6c7fd187f
Create Date: 2025-01-24 21:02:13.894590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c534224e57c1'
down_revision = '93a6c7fd187f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cours', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cours_filconducteur', 'FilConducteur', ['fil_conducteur_id'], ['id'])

    with op.batch_alter_table('GlobalGenerationSettings', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalGenerationSettings', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Cours', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cours_filconducteur', type_='foreignkey')

    # ### end Alembic commands ###
